# Generated by Django 5.0.2 on 2024-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description', max_length=1000),
        ),
    ]
